// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THTHU1_NET104.Models;

#nullable disable

namespace THTHU1_NET104.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("THTHU1_NET104.Models.Hang", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hangs");

                    b.HasData(
                        new
                        {
                            ID = "H1",
                            TenHang = "Roll Royces"
                        },
                        new
                        {
                            ID = "H2",
                            TenHang = "Balencicaca"
                        });
                });

            modelBuilder.Entity("THTHU1_NET104.Models.Oto", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("IDHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDHang");

                    b.ToTable("Otos");
                });

            modelBuilder.Entity("THTHU1_NET104.Models.Oto", b =>
                {
                    b.HasOne("THTHU1_NET104.Models.Hang", "Hang")
                        .WithMany()
                        .HasForeignKey("IDHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hang");
                });
#pragma warning restore 612, 618
        }
    }
}
